### PR TITLE
Rename the "last updated block" field of `NftAddressBalance` to match REST API

### PR DESCRIPTION
**Pull request by silasbw**
# Description

Example fix for REST API - SDK naming mismatch.

Fixes https://github.com/tatumio/tatum-js/issues/965

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by Smrecz** [comment]
@silasbw please, if you'd be so kind to also fix the usage in 
https://github.com/tatumio/tatum-js/blob/1785fa329c45e9f39a1217f2adb8e07af87c7b13/src/service/address/address.ts#L329-L330

and second instance in 
https://github.com/tatumio/tatum-js/blob/1785fa329c45e9f39a1217f2adb8e07af87c7b13/src/service/nft/nft.dto.ts#L158

**Comment by silasbw** [comment]
Updated, but isn't the second instance you point the one I updated in https://github.com/tatumio/tatum-js/pull/966/commits/fedde1af544c2598a9188fd2d389e42e9c9e03f3?

**Comment by Smrecz** [comment]
Yes, appologies, I meant
https://github.com/tatumio/tatum-js/blob/1785fa329c45e9f39a1217f2adb8e07af87c7b13/src/service/address/address.dto.ts#L33

**Comment by silasbw** [comment]
Updated with the assumption that the additional DTO you pointed out is also out of sync with the REST API response (I didn't confirm that because I don't think we call endpoints that use that DTO).

**Pull request merged**
