### PR TITLE
ALL-2078 Update RPC response types

### PR DESCRIPTION
**Pull request by oliverjantar**
# Description

Change response types for all RPC calls to return unmodified data

## Type of change
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by Smrecz** [comment]
Doesn't it have the same issue now, just with different wrapping object? I thought we'll be returning just the T from JsonRpcResponse<T> or an error.

**Comment by samuelsramko** [comment]
> 

We should return the full JSON RPC response here - which means format like this
`{
"id": number|string,
"jsonrpc":number|string,
"error"?: any
"result"?: any
}`

**Comment by oliverjantar** [comment]
It is returning what @samuelsramko mentioned, apart from Xrp that returns the result as it is - it doesn't have the "id" or "jsonRpc" fields.

**Comment by Smrecz** [comment]
Ok, so this is not wrapper, it's a DTO to cast to, I see now

**Review by Smrecz — APPROVED** [review]

**Pull request merged**
